routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('main');
Route::get('/post/{slug}', 'MainController@article')->name('post');
Route::get('/success', 'MainController@success')->name('success');
Route::get('/license', 'MainController@license')->name('license');
Route::post('/', 'CustomerController@store_public')->name('customer.store.public');

Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::middleware(['auth'])->group(function () {

    Route::get('article', 'ArticleController@index')->name('article.index');
    Route::post('article', 'ArticleController@store')->name('article.store');
    Route::get('article/create', 'ArticleController@create')->name('article.create');
    Route::get('article/{slug}', 'ArticleController@show')->name('article.show');
    Route::put('article/{slug}', 'ArticleController@update')->name('article.update');
    Route::delete('article/{slug}', 'ArticleController@destroy')->name('article.destroy');
    Route::get('article/{slug}/edit', 'ArticleController@edit')->name('article.edit');
    Route::post('article/{customer}', 'OrderController@store')->name('order.store');

    Route::resource('customer', 'CustomerController');

    Route::get('count/customer/default', 'CustomerController@count_default')->name('count.customer.default');

    Route::resource('status', 'StatusController', [
        'except' => ['edit']
    ]);

    Route::resource('product', 'ProductController', [
        'except' => ['edit']
    ]);

    Route::resource('construction', 'ConstructionController', [
        'except' => ['edit']
    ]);
    Route::resource('furniture', 'FurnitureController', [
        'except' => ['edit']
    ]);
    Route::resource('profile', 'ProfileController', [
        'except' => ['edit']
    ]);
    Route::resource('glass', 'GlassController', [
        'except' => ['edit']
    ]);
});

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    protected $table = 'status';

    protected $fillable = ['name', 'color'];

    public function customers()
    {
        return $this->hasMany('App\Customer');
    }
}

app/Http/Controllers/StatusController.php
<?php

namespace App\Http\Controllers;

use App\Status;
use Illuminate\Http\Request;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $collection = Status::paginate(10);

        return view('admin.status.index', compact('collection'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.status.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = new Status($request->all());
        $model->save();

        return redirect()->route('status.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Status::findOrFail($id);

        return view('admin.status.show', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Status::findOrFail($id);

        $model->update($request->all());

        return view('admin.status.show', compact('model'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Status::findOrFail($id)->delete();
        return redirect()->route('status.index');
    }
}

resources/views/admin/status/create.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Статус клиента</h3>
                            <form class="form-sample" method="POST" action="{{ route('status.store') }}">
                                {{ csrf_field() }}
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Название статуса</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="name" class="form-control">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div id="container" >
                                                    
                                            <div id="picker" class="block">
                                                            
                                                <div class="ui-color-picker" data-topic="picker"
                                                     data-mode="HSL"></div>
                                                            
                                                <div id="picker-samples" sample-id="master"></div>
                                                            
                                                <div id="controls">
                                                                    
                                                    <div id="delete">
                                                                            
                                                        <div id="trash-can"></div>
                                                                        
                                                    </div>
                                                                     
                                                    <div id="void-sample" class="icon-palette"></div>
                                                                
                                                </div>
                                                        
                                            </div>
                                                
                                        </div>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mr-2">Сохранить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection


@section('footer')
    <link rel="stylesheet" href="{{ URL::asset('css/admin/color-picker.css') }}">
    <script src="{{ URL::asset('js/admin/color-picker.js') }}"></script>

    <script>
        const picker = new ColorPicker({
            dom: document.getElementById('picker'),
            value: '#0F0'
        });

    </script>
@endsection

resources/views/admin/status/index.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Статусы клиентов</h3>
                            <a href="{{ route('status.create') }}" class="btn btn-sm btn-primary text-white">Создать</a>
                            <div class="table-responsive my-5">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>
                                            id
                                        </th>
                                        <th>
                                            Название статуса
                                        </th>
                                        <th>
                                            Цвет
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($collection as $model)
                                            <tr>
                                                <td class="py-1">
                                                    {{ $model->id }}
                                                </td>
                                                <td>
                                                    {{ $model->name }}
                                                </td>
                                                <td style="background-color: #{{ $model->color }};">
                                                </td>
                                                <td style="text-align: right; ">
                                                    <form class="d-inline" action="{{ route('status.destroy', ['id' => $model->id]) }}" method="POST">
                                                        {{method_field('DELETE')}}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
                                                    </form>
                                                    <a href="{{ route('status.show', ['id' => $model->id]) }}" class="btn btn-sm btn-primary color-white">Изменить</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>


                            <div class="d-flex justify-content-center">
                                {{ $collection->links('layouts.pagination') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection

resources/views/admin/status/show.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Статус клиента</h3>
                            <form class="form-sample" method="POST" action="{{ route('status.update', ['id' => $model->id]) }}">
                                {{method_field('PUT')}}
                                {{ csrf_field() }}
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Название статуса</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="name" value="{{ $model->name }}" class="form-control">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div id="container" >
                                                    
                                            <div id="picker" class="block">
                                                            
                                                <div class="ui-color-picker" data-topic="picker"
                                                     data-mode="HSL"></div>
                                                            
                                                <div id="picker-samples" sample-id="master"></div>
                                                            
                                                <div id="controls">
                                                                    
                                                    <div id="delete">
                                                                            
                                                        <div id="trash-can"></div>
                                                                        
                                                    </div>
                                                                     
                                                    <div id="void-sample" class="icon-palette"></div>
                                                                
                                                </div>
                                                        
                                            </div>
                                                
                                        </div>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mr-2">Обновить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection


@section('footer')
    <link rel="stylesheet" href="{{ URL::asset('css/admin/color-picker.css') }}">
    <script src="{{ URL::asset('js/admin/color-picker.js') }}"></script>

    <script>
        const picker = new ColorPicker({
            dom: document.getElementById('picker'),
            value: '#{{ $model->color }}'
        });

    </script>
@endsection