routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('main');
Route::get('/post/{slug}', 'MainController@article')->name('post');
Route::get('/success', 'MainController@success')->name('success');
Route::get('/license', 'MainController@license')->name('license');
Route::post('/', 'CustomerController@store_public')->name('customer.store.public');

Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::middleware(['auth'])->group(function () {

    Route::get('article', 'ArticleController@index')->name('article.index');
    Route::post('article', 'ArticleController@store')->name('article.store');
    Route::get('article/create', 'ArticleController@create')->name('article.create');
    Route::get('article/{slug}', 'ArticleController@show')->name('article.show');
    Route::put('article/{slug}', 'ArticleController@update')->name('article.update');
    Route::delete('article/{slug}', 'ArticleController@destroy')->name('article.destroy');
    Route::get('article/{slug}/edit', 'ArticleController@edit')->name('article.edit');
    Route::post('article/{customer}', 'OrderController@store')->name('order.store');

    Route::resource('customer', 'CustomerController');

    Route::get('count/customer/default', 'CustomerController@count_default')->name('count.customer.default');

    Route::resource('status', 'StatusController', [
        'except' => ['edit']
    ]);

    Route::resource('product', 'ProductController', [
        'except' => ['edit']
    ]);

    Route::resource('construction', 'ConstructionController', [
        'except' => ['edit']
    ]);
    Route::resource('furniture', 'FurnitureController', [
        'except' => ['edit']
    ]);
    Route::resource('profile', 'ProfileController', [
        'except' => ['edit']
    ]);
    Route::resource('glass', 'GlassController', [
        'except' => ['edit']
    ]);
});

app/Http/Controllers/GlassController.php
<?php

namespace App\Http\Controllers;

use App\Glass;
use Illuminate\Http\Request;

class GlassController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $collection = Glass::paginate(10);

        return view('admin.glass.index', compact('collection'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.glass.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = new Glass($request->all());
        $model->save();

        return redirect()->route('glass.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Glass::findOrFail($id);

        return view('admin.glass.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Glass::findOrFail($id);
        $model->update($request->all());

        return redirect()->route('glass.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Glass::findOrFail($id)->delete();

        return redirect()->route('glass.index');
    }
}

resources/views/admin/glass/create.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Создать стеклопакет</h3>
                            <form class="form-sample" method="POST" action="{{ route('glass.store') }}">
                                {{ csrf_field() }}
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Название стеклопакета</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="name" value="{{ old('name') }}" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Описание стеклопакета</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="description" value="{{ old('description') }}" class="form-control">
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mr-2">Сохранить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection

resources/views/admin/glass/index.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Стеклопакет</h3>
                            <a href="{{ route('glass.create') }}" class="btn btn-sm btn-primary text-white">Создать</a>
                            <div class="table-responsive my-5">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>
                                            id
                                        </th>
                                        <th>
                                            Название
                                        </th>
                                        <th>
                                            Описание
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($collection as $model)
                                            <tr>
                                                <td class="py-1">
                                                    {{ $model->id }}
                                                </td>
                                                <td>
                                                    {{ $model->name }}
                                                </td>
                                                <td>
                                                    {{ $model->description }}
                                                </td>
                                                <td style="text-align: right; ">
                                                    <form class="d-inline" action="{{ route('glass.destroy', ['id' => $model->id]) }}" method="POST">
                                                        {{method_field('DELETE')}}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
                                                    </form>
                                                    <a href="{{ route('glass.show', ['id' => $model->id]) }}" class="btn btn-sm btn-primary color-white">Изменить</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>


                            <div class="d-flex justify-content-center">
                                {{ $collection->links('layouts.pagination') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection

resources/views/admin/glass/show.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Стеклопакет</h3>
                            <form class="form-sample" method="POST" action="{{ route('glass.update', ['id' => $model->id]) }}">
                                {{method_field('PUT')}}
                                {{ csrf_field() }}
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Название стеклопакета</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="name" value="{{ $model->name }}" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Описание стеклопакета</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="description" value="{{ $model->description }}" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mr-2">Сохранить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection