routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('main');
Route::get('/post/{slug}', 'MainController@article')->name('post');
Route::get('/success', 'MainController@success')->name('success');
Route::get('/license', 'MainController@license')->name('license');
Route::post('/', 'CustomerController@store_public')->name('customer.store.public');

Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::middleware(['auth'])->group(function () {

    Route::get('article', 'ArticleController@index')->name('article.index');
    Route::post('article', 'ArticleController@store')->name('article.store');
    Route::get('article/create', 'ArticleController@create')->name('article.create');
    Route::get('article/{slug}', 'ArticleController@show')->name('article.show');
    Route::put('article/{slug}', 'ArticleController@update')->name('article.update');
    Route::delete('article/{slug}', 'ArticleController@destroy')->name('article.destroy');
    Route::get('article/{slug}/edit', 'ArticleController@edit')->name('article.edit');
    Route::post('article/{customer}', 'OrderController@store')->name('order.store');

    Route::resource('customer', 'CustomerController');

    Route::get('count/customer/default', 'CustomerController@count_default')->name('count.customer.default');

    Route::resource('status', 'StatusController', [
        'except' => ['edit']
    ]);

    Route::resource('product', 'ProductController', [
        'except' => ['edit']
    ]);

    Route::resource('construction', 'ConstructionController', [
        'except' => ['edit']
    ]);
    Route::resource('furniture', 'FurnitureController', [
        'except' => ['edit']
    ]);
    Route::resource('profile', 'ProfileController', [
        'except' => ['edit']
    ]);
    Route::resource('glass', 'GlassController', [
        'except' => ['edit']
    ]);
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'product';

    protected $fillable = [
        'title', 'description', 'price', 'show'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function construction()
    {
        return $this->belongsTo('App\Construction', 'construction_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function profile()
    {
        return $this->belongsTo('App\Profile', 'profile_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function furniture()
    {
        return $this->belongsTo('App\Furniture', 'furniture_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function glass()
    {
        return $this->belongsTo('App\Glass', 'glass_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Construction;
use App\Furniture;
use App\Glass;
use App\Product;
use App\Profile;
use App\Rules\ProfileDependencies;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $collection = Product::paginate(10);

        return view('admin.product.index', compact('collection'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $constructions = Construction::all();
        $profiles = Profile::all();
        $furnitures = Furniture::all();
        $glasses = Glass::all();

        return view('admin.product.create',
            compact('constructions', 'profiles', 'furnitures', 'glasses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $request->validate([
            'profile' => 'required|numeric',
            'furniture' => ['required', new ProfileDependencies($data['profile'])],
            'glass' => ['required', new ProfileDependencies($data['profile'])],
        ]);

        $model = new Product($data);

        $model->construction()->associate(Construction::find($data['construction']));
        $model->profile()->associate(Profile::find($data['profile']));
        $model->furniture()->associate(Furniture::find($data['furniture']));
        $model->glass()->associate(Glass::find($data['glass']));

        $model->save();

        if ($model->title == null) {
            $model->title = $model->construction->name . ' ' .
                $model->profile->name . ' ' . $model->furniture->name . ' ' .
                $model->glass->name;
            $model->save();
        }

        if ($model->description == null) {
            $model->description = $model->construction->name . "\n" .
                'Профиль: ' . $model->profile->name . "\n" . 'Фурнитура: ' . $model->furniture->name . "\n" .
                'Стеклопакет: ' . $model->glass->name  . "\n" . 'Цена: ' . $model->price;
            $model->save();
        }

        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        $constructions = Construction::all();
        $profiles = Profile::all();
        $furnitures = Furniture::all();
        $glasses = Glass::all();

        return view('admin.product.show',
            compact('constructions', 'profiles', 'furnitures', 'glasses', 'product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $request->validate([
            'profile' => 'required|numeric',
            'furniture' => ['required', new ProfileDependencies($data['profile'])],
            'glass' => ['required', new ProfileDependencies($data['profile'])],
        ]);

        $model = Product::findOrFail($id);
        $model->update($data);

        $model->construction()->associate(Construction::find($data['construction']));
        $model->profile()->associate(Profile::find($data['profile']));
        $model->furniture()->associate(Furniture::find($data['furniture']));
        $model->glass()->associate(Glass::find($data['glass']));

        $model->save();

        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::findOrFail($id)->delete();

        return redirect()->route('product.index');
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Создать продукт</h3>
                            <form class="form-sample" method="POST" action="{{ route('product.store') }}">
                                {{ csrf_field() }}
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Заголовок продукта</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="title" value="{{ old('title') }}"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Описание продукта</label>
                                            <div class="col-sm-9">
                                                <textarea rows="6" name="description" class="form-control">{{ old('description') }}</textarea>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Цена</label>
                                            <div class="col-sm-9">
                                                <input type="number" name="price" value="{{ old('price') }}"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">
                                                Показывать
                                            </label>
                                            <div class="col-sm-9">
                                                <input type="hidden" name="show" value="0">
                                                @if(null != old('show'))
                                                    @if(old('show'))
                                                        <input type="checkbox" checked name="show" value="1" class="form-check-input">
                                                    @else
                                                        <input type="checkbox" name="show" value="1" class="form-check-input">
                                                    @endif
                                                @else
                                                    <input type="checkbox" checked name="show" value="1" class="form-check-input">
                                                @endif
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Конструкция</label>
                                            <div class="col-sm-9">
                                                <select name="construction" class="form-control">
                                                    @foreach($constructions as $model)
                                                        <option value="{{ $model->id }}">
                                                            {{ $model->name }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Профиль</label>
                                            <div class="col-sm-9">
                                                <select name="profile" class="form-control">
                                                    @foreach($profiles as $model)
                                                        <option value="{{ $model->id }}">
                                                            {{ $model->name }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Фурнитура</label>
                                            <div class="col-sm-9">
                                                <select name="furniture" class="form-control">
                                                    @foreach($furnitures as $model)
                                                        <option value="{{ $model->id }}">
                                                            {{ $model->name }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Стеклопакет</label>
                                            <div class="col-sm-9">
                                                <select name="glass" class="form-control">
                                                    @foreach($glasses as $model)
                                                        <option value="{{ $model->id }}">
                                                            {{ $model->name }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mr-2">Сохранить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection

resources/views/admin/product/index.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Продукты</h3>
                            <a href="{{ route('product.create') }}" class="btn btn-sm btn-primary text-white">Создать</a>
                            <div class="table-responsive my-5">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>
                                            id
                                        </th>
                                        <th>
                                            Конструкция
                                        </th>
                                        <th>
                                            Профиль
                                        </th>
                                        <th>
                                            Фурнитура
                                        </th>
                                        <th>
                                            Стеклопакет
                                        </th>
                                        <th>
                                            Цена
                                        </th>
                                        <th>
                                            Показывать
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($collection as $model)
                                            <tr>
                                                <td class="py-1">
                                                    {{ $model->id }}
                                                </td>
                                                <td>
                                                    {{ $model->construction->name }}
                                                </td>
                                                <td>
                                                    {{ $model->profile->name }}
                                                </td>
                                                <td>
                                                    {{ $model->furniture->name }}
                                                </td>
                                                <td>
                                                    {{ $model->glass->name }}
                                                </td>
                                                <td>
                                                    @if( $model->show )
                                                        +
                                                    @else
                                                        -
                                                    @endif
                                                </td>
                                                <td style="text-align: right; ">
                                                    <form class="d-inline" action="{{ route('product.destroy', ['id' => $model->id]) }}" method="POST">
                                                        {{method_field('DELETE')}}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
                                                    </form>
                                                    <a href="{{ route('product.show', ['id' => $model->id]) }}" class="btn btn-sm btn-primary color-white">Изменить</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>


                            <div class="d-flex justify-content-center">
                                {{ $collection->links('layouts.pagination') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection

resources/views/admin/product/show.blade.php
@extends('admin.dashboard.app')

@section('content')

    <!-- partial -->
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Фурнтура</h3>
                            <form class="form-sample" method="POST" action="{{ route('product.update', ['id' => $product->id]) }}">
                                {{method_field('PUT')}}
                                {{ csrf_field() }}
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Заголовок продукта</label>
                                            <div class="col-sm-9">
                                                <input type="text" name="title" value="{{ $product->title }}" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Описание продукта</label>
                                            <div class="col-sm-9">
                                                <textarea rows="6" type="text" name="description" class="form-control">{{ $product->description }}</textarea>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Цена</label>
                                            <div class="col-sm-9">
                                                <input type="number" name="price" value="{{ $product->price }}"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">
                                                Показывать
                                            </label>
                                            <div class="col-sm-9">
                                                <input type="hidden" name="show" value="0">
                                                @if($product->show)
                                                    <input type="checkbox" checked name="show" value="1" class="form-check-input">
                                                @else
                                                    <input type="checkbox" name="show" value="1" class="form-check-input">
                                                @endif
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Конструкция</label>
                                            <div class="col-sm-9">
                                                <select name="construction" class="form-control">
                                                    @foreach($constructions as $model)
                                                        @if($model->id == $product->construction_id)
                                                            <option selected="selected" value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @else
                                                            <option
                                                                    value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @endif
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Профиль</label>
                                            <div class="col-sm-9">
                                                <select name="profile" class="form-control">
                                                    @foreach($profiles as $model)
                                                        @if($model->id == $product->profile_id)
                                                            <option selected="selected"
                                                                    value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @else
                                                            <option
                                                                value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @endif
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Фурнитура</label>
                                            <div class="col-sm-9">
                                                <select name="furniture" class="form-control">
                                                    @foreach($furnitures as $model)
                                                        @if($model->id == $product->furniture_id)
                                                            <option selected="selected"
                                                                    value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @else
                                                            <option
                                                                value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @endif
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Стеклопакет</label>
                                            <div class="col-sm-9">
                                                <select name="glass" class="form-control">
                                                    @foreach($glasses as $model)
                                                        @if($model->id == $product->glass_id)
                                                            <option selected="selected"
                                                                    value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @else
                                                            <option
                                                                value="{{ $model->id }}">
                                                                {{ $model->name }}
                                                            </option>
                                                        @endif
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mr-2">Сохранить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->

        @include('admin.dashboard.footer')
    </div>
    <!-- main-panel ends -->

@endsection